apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reconnator
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - "--target"
              - {{ .Values.targetDomain | quote }}
            envFrom:
            - secretRef:
                name: {{ .Release.Name }}-telegram-secret
          restartPolicy: OnFailure