apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telegram-secret
type: Opaque
data:
  # Encoding biar ga di intip orang, malu
  TELEGRAM_BOT_TOKEN: {{ default "" .Values.telegram.botToken | b64enc | quote }}
  TELEGRAM_CHAT_ID: {{ default "" .Values.telegram.chatId | b64enc | quote }}